version: 2.1 

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: bookstore_test
caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle
      - run: mv config/database.circleci config/database.yml
      - run:
          name: Database Setup
          command: |
            bin/rails db:create db:schema:load --trace
            bin/rails db:migrate
  run_rubocop:
    description: command to start rubocop
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_brakeman:
    description: command to start brakeman
    steps:
      - run:
          name: brakeman
          command: bundle exec brakeman
  run_bundler-audit:
    description: command to start bundler-audit
    steps:
      - run:
          name: bundler-audit
          command: bundle exec bundler-audit
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec/rspec.xml
          when: always
      - store_test_results:
          path: /tmp/test-results/rspec/
jobs:
  rubocop:
    executor: default
    steps:
      - defaults
      - run_rubocop
  specs:
    executor: default
    steps:
      - defaults
      - run_specs
  brakeman:
    executor: default
    steps:
      - defaults
      - run_brakeman
  bundler-audit:
    executor: default
    steps:
      - defaults
      - run_bundler-audit

workflows:
  version: 2.1
  build:
    jobs:
      - brakeman
      - bundler-audit
      - rubocop:
          requires:
            - brakeman
            - bundler-audit
      - specs:
          requires:
            - rubocop
